//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.yyyyy7773
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Dsss2.
    /// </summary>
    //  *** Start programmer edit section *** (dsss2 CustomAttributes)

    //  *** End programmer edit section *** (dsss2 CustomAttributes)
    [AutoAltered()]
    [Caption("Dsss2")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("dsss2E", new string[0])]
    [View("dsss2L", new string[0])]
    public class dsss2 : ICSSoft.STORMNET.DataObject
    {
        
        //  *** Start programmer edit section *** (dsss2 CustomMembers)

        //  *** End programmer edit section *** (dsss2 CustomMembers)

        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "dsss2E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View dsss2E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("dsss2E", typeof(IIS.yyyyy7773.dsss2));
                }
            }
            
            /// <summary>
            /// "dsss2L" view.
            /// </summary>
            public static ICSSoft.STORMNET.View dsss2L
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("dsss2L", typeof(IIS.yyyyy7773.dsss2));
                }
            }
        }
    }
}
